### ISSUE TITLE
Tengja gagnagrunn inn í spring

### ISSUE THREAD

**Issue by hag56** [gisli94/Draumaradningar#1]
Það gengur illa hjá mér að tengja við DatabaseController.
smkv http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-sql.html 
þá ætti að vera hægt, til að tengja spring við gagnagrunninn, að setja ( i application.properties) -
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://horton.elephantsql.com:5432/...
spring.datasource.username=...
spring.datasource.password=...

og nota svo JDBC til að sækja og uppfæra
http://docs.spring.io/spring/docs/current/spring-framework-reference/html/jdbc.html

-Mér tekst að tengja þetta svona og þá býr spring til users töflu smkv @Entity og @Table(name=users)

**Comment by gisli94** [comment]
Kemur einhver villa?

**Comment by hag56** [comment]
meinarðu við DatabaseController ? nei, ekki villa, en þarf ekki að stofna nýjan controller og connection fyrir hverja query? 
svona er þetta byggt inn í spring með @Entity ofl og hentugt að nota það þannig.

![image](https://cloud.githubusercontent.com/assets/9433583/20039245/a2803812-a438-11e6-96d2-6cd170fd926d.png)

**Comment by gisli94** [comment]
Þú býrð bara til einn DatabaseController í byrjuninni á java forritinu? Ég skil ekki alveg hvað vandamálið var?

**Comment by hag56** [comment]
reyndar vantar einhver dependencies í gradle.build í þennann kóða frá mér

**Comment by hag56** [comment]
ertu að meina í Application? eða ertu að meina að búa til nýjan databaseController í usercontroller (til að geta skráð og athugað password) og nýjan databaseController í dreamController (til að geta flett upp og skráð drauma)  os.frv?
Við erum ekki að nýta spring með þetta þannig

**Comment by gisli94** [comment]
Ég var viljandi að halda gagnagrunninum frá spring því Gunnar benti mér á að það væri margfalt einfaldara og ólíklegra að það komi upp skrítnar villur.
Fyrir þær javaskrár sem notast við gagnagrunninn að einhverju leiti búum við bara til nýjan DatabaseController, það er ekki eins og það sé eitthvað vesen.

**Comment by hag56** [comment]
ok, það er ástæðan fyrir að nota ekki innbyggða functionalityið. 
no prob. :)
